name: "Lint, Test and deploy"
on: [push, workflow_dispach]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: build
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Preview
        run: npm run preview  
      - name: Deploy
        run: echo "Deploying ..."
